/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package com.srms.dao;

import com.srms.model.Student;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author krisha
 */
@WebServlet(name = "StudentDAO", urlPatterns = {"/StudentDAO"})
public interface StudentDAO {

 

    /**
     * Insert a new student into the database.
     * @param student Student object with all fields set (id auto-generated by DB)
     * @return true if insert succeeded, false otherwise
     */
    boolean addStudent(Student student);

    /**
     * Retrieve all students from the database.
     * @return List of all Student objects
     */
    List<Student> getAllStudents();

    /**
     * Retrieve a single student by their ID.
     * @param id Primary key of the student
     * @return Student object if found, null otherwise
     */
    Student getStudentById(int id);

    /**
     * Search students by name (partial match).
     * @param name Search keyword
     * @return List of matching Student objects
     */
    List<Student> searchStudentsByName(String name);

    /**
     * Update an existing student record.
     * @param student Student object with updated fields (id must be set)
     * @return true if update succeeded, false otherwise
     */
    boolean updateStudent(Student student);

    /**
     * Delete a student by their ID.
     * @param id Primary key of the student to delete
     * @return true if delete succeeded, false otherwise
     */
    boolean deleteStudent(int id);

    /**
     * Count total number of students.
     * @return Total student count
     */
    int getTotalCount();
}

   

    

